### ISSUE TITLE
Sharing the Step file?

### ISSUE THREAD

**Issue by niccoswe** [protomaker964/Rhino-FFB-Clone-3D_Printed#2]
Hi! Great design and work. Would you mind sharing the STEP file so that i could adjust the clearences for my printer? Thank you in advance.

**Comment by protomaker964** [comment]
The Stp file is massive and not something I could upload.
The STL files when converted to solids, are easily adjusted in your favorite editor.

**Comment by musseilm** [comment]
Im also interested in the step file. Any chance your would reconsider uploading that? Or share it somewhere?

Thank you
